- name: React to comment
  uses: dkershner6/reaction-action@v1
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    commentId: 1234 # Optional if the trigger is a comment. Use another action to find this otherwise.
    reaction: "hooray" # Optional, defaults to +1
